In [1]:
import numpy as np

# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Replace all the elements in the third column with 1
array[:, 2] = 1 #array[rows, columns]
print("Modified array:")
print(array)

Original array:
[[14 10  5 19  5]
 [15 20  1  5  4]
 [16 17 10 11  5]
 [ 9 16  7 13  4]
 [ 2 13  5  7 13]]
Modified array:
[[14 10  1 19  5]
 [15 20  1  5  4]
 [16 17  1 11  5]
 [ 9 16  1 13  4]
 [ 2 13  1  7 13]]


In [2]:
# Create a NumPy array of shape (4, 4) with values from 1 to 16
array = np.arange(1, 17).reshape((4, 4))
print("Original array:")
print(array)

# Replace the diagonal elements with 0
np.fill_diagonal(array, 0)
print("Modified array:")
print(array)

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Modified array:
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [3]:
# Create a NumPy array of shape (6, 6) with values from 1 to 36
array = np.arange(1, 37).reshape((6, 6))
print("Original array:")
print(array)

# Extract the sub-array
sub_array = array[2:5, 1:4]
print("Sub-array:")
print(sub_array)

Original array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Sub-array:
[[14 15 16]
 [20 21 22]
 [26 27 28]]
